name: First Workflow

on:
 workflow_dispatch:

jobs:
 job1:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1
      run: |
        echo "Step 1"

    - name: Step 2
      run: |
        echo "Step 2"

 job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Run Cowsay
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'Hello, Team 16!'
        color: 'grey'
        